### ISSUE TITLE
Support plugins too

### ISSUE THREAD

**Issue by randycoulman** [kentcdodds/eslint-find-new-rules#14]
Thanks for this super-useful tool!  I maintain a pluggable configuration for my company, and this tool is already worth its weight in gold!

We use some additional plugins in our configuration (like eslint-plugin-react and eslint-plugin-import), and it would be great if we could look for missing rules from those plugins as well.

**Comment by kentcdodds** [comment]
Hi @randycoulman! I'm pleased you like it! I should rename #1 because the work we're putting into that will support plugins. Feel free to help out and [makeapullrequest.com](http://makeapullrequest.com) :-)

**Comment by kentcdodds** [comment]
Turns out there is a bit more work to make this find `plugin` rules as well. Re-opening :-)

**Comment by ta2edchimp** [comment]
Had a look into this today and I hope to get the time to work on it tomorrow.
Just in case, I'll leave this here, as an entry point for further investigations:

Every plugin, that brings along a new set of rules, exposes these via a `rules` property of its module's exported object (see [Rules in Plugins](http://eslint.org/docs/developer-guide/working-with-plugins)).
