### ISSUE TITLE
Ghooks config erroneous

### ISSUE THREAD

**Issue by ta2edchimp** [kentcdodds/eslint-find-new-rules#21]
There's a typo within `commit-msg` in [`package.json`](https://github.com/kentcdodds/eslint-find-new-rules/blob/master/package.json#L64).
Furthermore, if I don't miss anything, the ghooks config should be contained within `config.ghooks`, not `config`.

While we're at it, would it be a good idea to make the hooks "`opt-out`able"?

**Comment by sarbbottam** [comment]
I guess you are correct, should be something like https://github.com/kentcdodds/webpack-validator/blob/master/package.json#L90-L97

**Comment by kentcdodds** [comment]
:sweat_smile: whoops. Mind making a PR? I'd love to see it opt-out able :-)

**Comment by kentcdodds** [comment]
Actually, I'd prefer opt-in :+1:

**Comment by ta2edchimp** [comment]
Won't be until tomorrow or thursday that I could do this myself.
If @sarbbottam wants to give it a try (see [opt-cli](http://npm.im/opt-cli) for the opt-in/out module) please report it back here (I'd do it otherwise, but not before tomorrow).

**Comment by sarbbottam** [comment]
I can take it up in the evening.
