### ISSUE TITLE
Empty list when using `extends: "eslint:recommended"`

### ISSUE THREAD

**Issue by jfmengels** [kentcdodds/eslint-find-new-rules#24]
I have a config where I use ESLint's recommended settings, but I want to list all the other rules and put them all in my config, so that I can turn them on some time later. Problem, when I extend the recommend list, (and with only just that)

``` json
module.exports = {
    "extends": "eslint:recommended"
}
```

then I get nothing back, as all rules are then considered to be set (most of them to "off"). Is this by design?

ESLint v2.4.0
eslint-find-new-rules v1.2.0

**Comment by sarbbottam** [comment]
> > Is this by design?

In short, Yes.

By using `"eslint:recommended"` you are using all the rules available in `eslint`, there are no unused rules.

**Comment by kentcdodds** [comment]
What @sarbbottam said. Because you are extending something that explicitly defines all the rules, you don't have any undefined rules. Good job! :dancer:

**Comment by sarbbottam** [comment]
> > I want to list all the other rules

We could expose something like `listAllRules`, but I am not sure, if that would be semantically aligned with the `package name`

**Comment by kentcdodds** [comment]
If you are going to configure all rules anyway, there's no reason to extend `eslint:recommended` because your rule definitions will override those rules anyway.

**Comment by jfmengels** [comment]
True, but I wanted to define all the other rules, as I don't know the options given (if any) to those rules. I always thought ESLint just set the rules it wanted on, and left out the others, that's why I was surprised I didn't see the other rules listed here.

I don't mind copying the recommended list,, but haven't yet found an easy way to do that (you can't copy-paste it from ESLint's website or project). I just console.logged stuff in the middle of the process of this tool and got it, but that's the "easiest"way I've found. Will do that I guess, thanks :)

**Comment by ta2edchimp** [comment]
When I remember correctly, `eslint:recommended` maps to [`eslint/conf/eslint.json`](https://github.com/eslint/eslint/blob/master/conf/eslint.json).
Every rule within [`eslint/lib/rules`](https://github.com/eslint/eslint/tree/master/lib/rules) should be mentioned and configured (~209 in total).

**Comment by jfmengels** [comment]
I thought it was computed dynamically as I was seeing a recommended flag in core rules (e.g https://github.com/eslint/eslint/blob/master/lib/rules/array-bracket-spacing.js#L22)
Thanks a lot!

**Comment by ta2edchimp** [comment]
I reopen this to be visible as "FAQ".

**Comment by kentcdodds** [comment]
Closing because this module is no longer maintained, please use https://github.com/sarbbottam/eslint-find-rules
