### ISSUE TITLE
Would it it be ok to  have a more generic name for this module?

### ISSUE THREAD

**Issue by sarbbottam** [kentcdodds/eslint-find-new-rules#29]
Hi @kentcdodds, @ta2edchimp,  

Would it it be ok to  have a more generic name for this module and expose the all the functionalities via cli?

For example:

``` sh
rule-finder --current [path/to/eslint-config] // for current rules
rule-finder --unused [path/to/eslint-config] // for unused rules
rule-finder --plugin [path/to/eslint-config] // for plugin rules
rule-finder --all-available [path/to/eslint-config] // for all-available rules
```

---

If not, will be OK for me to create a separate module almost similar to this, with acknowledgement to this module?

Thanks!!

**Comment by kentcdodds** [comment]
Hey @sarbbottam! It's obvious you're more interested in making this awesome than I am. That's great! Why don't you fork this and create `eslint-rule-finder` or whatever, then make a PR to this repo to add a reference to that project and label it as deprecated. Then I'll go ahead and deprecate the package and point to yours. Sound good?

**Comment by sarbbottam** [comment]
Thanks!! Would update the thread once done.

**Comment by ta2edchimp** [comment]
@sarbbottam I like the idea! I can even think of some additional options like to exit with non-zero codes on certain occasions (ensure all rules are configured), more verbose / detailed output, etc.

:+1:

**Comment by sarbbottam** [comment]
@ta2edchimp sounds good!
