### ISSUE TITLE
Can it be used for .eslintrc files

### ISSUE THREAD

**Issue by 4kochi** [kentcdodds/eslint-find-new-rules#31]
I have a project with a .eslintrc file which includes all rules. Now I want to check if there are some new rules when there is a new release of `eslint`.

I have tried `./node_modules/.bin/eslint-find-new-rules .eslintrc`, but there is not output. I am not sure if this is a valid use case for this module or if i am doing it wrong.

Thanks for your help.

**Comment by ta2edchimp** [comment]
Yes, this is absolutely a valid use case.
There'll be an output (and a non-zero exit code) _only_ if there are rules that are not covered by the eslint config specified. As you said the specified eslintrc does include all rules, so there's no output.

**Comment by 4kochi** [comment]
Ok, thanks. It works partly in my case. If i use the following `.eslintrc` file, there is no output in the console. But since `"eslint:recommended"` does only include a few rules i would expect the module to tell me which other rules are missing.

```
{
    "extends": "eslint:recommended",
    "env": {
        "node": true,
        "browser": true
    },
    "rules": {
    },
    "globals": {
        "afterEach": false,
        "angular": false,
        "beforeEach": false,
        "browser": false,
        "by": false,
        "element": false,
        "expect": false,
        "describe": false,
        "FileList": false,
        "inject": false,
        "it": false,
        "jasmine": false,
        "lxHelpers": false,
        "spyOn": false,
        "UAParser": false,
        "xdescribe": false,
        "xit": false
    }
}
```

If i use the same `.eslintrc` but without specifying `"extends": "eslint:recommended"`, it works fine and all rules missing are displayed.

**Comment by ta2edchimp** [comment]
In fact, `eslint:recommended` maps to [`eslint/conf/eslint.json`](https://github.com/eslint/eslint/blob/master/conf/eslint.json). Every rule within `eslint/lib/rules` should be mentioned and configured in there (~209 in total / that also takes "deactivated" rules into account).

**Comment by ta2edchimp** [comment]
May be for the reworked version @sarbbottam wanted to fork from this one, we may implement some kind of comparison / diff tool, that shows the differences between multiple eslint configurations.
At least, it's something I already thought about.

**Comment by sarbbottam** [comment]
@ta2edchimp @4kochi absolutely, I plan to raise the first PR, by EOD, a bit tied up at work.

**Comment by kentcdodds** [comment]
Closing because this module is no longer maintained, please use https://github.com/sarbbottam/eslint-find-rules
