### ISSUE TITLE
TypeError: predicate is not a function

### ISSUE THREAD

**Issue by MoOx** [kentcdodds/eslint-find-new-rules#32]
Not sure if it's really `eslint-find-new-rules` the culprit here but it looks like it is according to the stack trace:

```
.../eslint-config-i-am-meticulous/node_modules/lodash.difference/node_modules/lodash._baseflatten/index.js:73
    if (depth > 0 && predicate(value)) {
                     ^

TypeError: predicate is not a function
    at baseFlatten (.../eslint-config-i-am-meticulous/node_modules/lodash.difference/node_modules/lodash._baseflatten/index.js:73:22)
    at .../eslint-config-i-am-meticulous/node_modules/lodash.difference/index.js:73:29
    at .../eslint-config-i-am-meticulous/node_modules/lodash.rest/index.js:112:27
    at findNewRules (.../eslint-config-i-am-meticulous/node_modules/eslint-find-new-rules/index.js:17:10)
    at Object.<anonymous> (.../eslint-config-i-am-meticulous/node_modules/eslint-find-new-rules/bin.js:14:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
.../eslint-config-i-am-meticulous/node_modules/npmpub/npmpub.js:204
        throw err
        ^

Error: 'npm test' failed.
    at .../eslint-config-i-am-meticulous/node_modules/npmpub/npmpub.js:157:15
```

Any idea?

**Comment by MoOx** [comment]
(I was about to make a release for `eslint-config-i-am-meticulous` with [npmpub](https://github.com/MoOx/npmpub) which `trash` node_modules and run tests before cutting a release. The test suit of `eslint-config-i-am-meticulous` include call to your package https://github.com/MoOx/eslint-config-i-am-meticulous/blob/915fe5de80674bdd54687db1672ffa1ade8f8937/package.json#L45

**Comment by ta2edchimp** [comment]
Thanks for the detailed report. Will have a look into this.

**Comment by MoOx** [comment]
To reproduce:

``` console
$ git clone https://github.com/MoOx/eslint-config-i-am-meticulous
$ cd eslint-config-i-am-meticulous
$ npm i
$ npm run check-update
```

**Comment by kentcdodds** [comment]
I definitely reproduced it. Don't have time to look into it right now. Also, the code has changed quite a bit since I wrote it :sweat_smile:

**Comment by kentcdodds** [comment]
Hopefully @ta2edchimp or @sarbbottam can figure out what's going on :-)

**Comment by sarbbottam** [comment]
Looks like an issue with `lodash.difference`, using an older version of `lodash._baseflatten` as dependency. Still digging ..., will update the thread with my findings.

**Comment by sarbbottam** [comment]
@MoOx could you update the `eslint-find-new-rules` version to [`2.0.1`](https://www.npmjs.com/package/eslint-find-new-rules) and try again?

**Comment by MoOx** [comment]
Working like a charm now https://travis-ci.org/MoOx/eslint-config-i-am-meticulous/jobs/122359997#L647
Thanks a lot for you work.

**Comment by sarbbottam** [comment]
Glad to hear that!

**Comment by zhuanghw-s** [comment]
你们说啥呢？？？
