### ISSUE TITLE
Release a new version with the deprecation warning at the top

### ISSUE THREAD

**Issue by mgol** [kentcdodds/eslint-find-new-rules#35]
The deprecation warning and a link to the package that supersedes this one is present in the README but hasn't been published to npm: https://www.npmjs.com/package/eslint-find-new-rules. I think it would be worthwhile to release a new patch with the warning.

Remember to re-invoke `npm deprecate eslint-find-new-rules "Your deprecation message"` after you do it.

**Comment by kentcdodds** [comment]
Good point

**Comment by kentcdodds** [comment]
Done

**Comment by mgol** [comment]
The deprecation message is cut off:

```
npm WARN deprecated eslint-find-new-rules@2.0.2: This
```

I suspect you didn't wrap the message in quotes. :)

**Comment by kentcdodds** [comment]
Thanks for testing it out. Fixed.

**Comment by jfmengels** [comment]
Thanks @mgol, I didn't know about this command. Just did it for my deprecated packages :)
