### ISSUE TITLE
npm run validate errors out at npm run check-coverage

### ISSUE THREAD

**Issue by sarbbottam** [kentcdodds/eslint-find-new-rules#9]
Am I the only one finding error for `npm run validate`, to be precise `npm run check-coverage`

`coverage` directory does exist, I have verified it with `npm run cover`.

```
ERROR: check-coverage: None-Zero Exit(1);

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "validate"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! eslint-find-new-rules@0.0.0-semantically-released validate: `npm-run-all --parallel lint cover --sequential check-coverage`
npm ERR! Exit status 1
```

---

```
吽 npm run check-coverage

> eslint-find-new-rules@0.0.0-semantically-released check-coverage /Users/sabandyo/GitHub/eslint-find-new-rules
> nyc check-coverage --statements 71 --branches 33 --functions 100 --lines 71

ERROR: No coverage files found.

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "check-coverage"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! eslint-find-new-rules@0.0.0-semantically-released check-coverage: `nyc check-coverage --statements 71 --branches 33 --functions 100 --lines 71`
npm ERR! Exit status 1
```

Thanks!!

**Comment by kentcdodds** [comment]
Nope, I'll bet this is the same issue as here:
https://github.com/kentcdodds/webpack-validator/issues/21
https://github.com/kentcdodds/configuration-validator/issues/9

Let me remove `check-coverage` from the `validate` script until we can work out what's going on... You're not on Windows are you? This is odd...

**Comment by sarbbottam** [comment]
> > You're not on Windows are you?

`OS X El Capitan (10.11.3)`

**Comment by sarbbottam** [comment]
This is strange, `nyc check-coverage` is working for me in the same `env` for another project. Let me dig a bit further.

**Comment by kentcdodds** [comment]
Note: I've pushed some updates so you should be able to [update](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch?series=how-to-contribute-to-an-open-source-project-on-github) your [fork](https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repository?series=how-to-contribute-to-an-open-source-project-on-github) :+1:

**Comment by sarbbottam** [comment]
Thanks for the video links, I generally do the following

```
remote add upstream git@github.com:kentcdodds/eslint-find-new-rules.git
fetch upstream
rebase upstream
```

[`addup = remote add upstream`](https://github.com/sarbbottam/conf-files/blob/master/git-confs/gitconfig#L32)
[`fetchup = fetch upstream`](https://github.com/sarbbottam/conf-files/blob/master/git-confs/gitconfig#L33)
[`rebaseup = rebase upstream/master`](https://github.com/sarbbottam/conf-files/blob/master/git-confs/gitconfig#L35)
